// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCky3ScZefRrWorG9QXe3Z5kTqaVkM6hzM',
    appId: '1:88052046038:web:e3b30934231babc8a41177',
    messagingSenderId: '88052046038',
    projectId: 'travelapplk',
    authDomain: 'travelapplk.firebaseapp.com',
    storageBucket: 'travelapplk.appspot.com',
    measurementId: 'G-2VG3NTRQ17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbhgjNtdmZy6e_kUHsxPc5BDgs17Rz9rg',
    appId: '1:88052046038:android:04e338d662938473a41177',
    messagingSenderId: '88052046038',
    projectId: 'travelapplk',
    storageBucket: 'travelapplk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfisRlo1VtOlxDPgn9WnxBnmu47MmwYiY',
    appId: '1:88052046038:ios:23b20e25dc62f0c4a41177',
    messagingSenderId: '88052046038',
    projectId: 'travelapplk',
    storageBucket: 'travelapplk.appspot.com',
    iosBundleId: 'com.example.travelfreeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfisRlo1VtOlxDPgn9WnxBnmu47MmwYiY',
    appId: '1:88052046038:ios:32dd784f3eb466bba41177',
    messagingSenderId: '88052046038',
    projectId: 'travelapplk',
    storageBucket: 'travelapplk.appspot.com',
    iosBundleId: 'com.example.travelfreeapp.RunnerTests',
  );
}
